version: '3'

services:
    db-postgres:
        image: 'postgres'
        restart: always
        container_name: db_postgres
        environment:
            POSTGRES_DB: 'coqui'
            POSTGRES_USER: 'root'
            POSTGRES_PASSWORD: 'root'
        ports:
            - '5432:5432'
        networks:
            coqui-networks:
                ipv4_address: 173.28.1.2
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M

    db-pgadmin:
        image: 'dpage/pgadmin4'
        restart: always
        container_name: db_pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: 'user@email.com'
            PGADMIN_DEFAULT_PASSWORD: 'user'
        ports:
            - '5433:80'
        depends_on:
            - db-postgres
        networks:
            coqui-networks:
                ipv4_address: 173.28.1.3
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M

    db-mongo:
        image: mongo
        restart: always
        container_name: mongo_db
        environment: 
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
        ports:
            - '27017:27017'
        networks:   
            coqui-networks:
                ipv4_address: 172.28.1.4
        deploy:
            resources:
                limits:
                    memory: 100M
                reservations:
                    memory: 20M

    db-nosqlclient:
        image: mongoclient/mongoclient
        restart: always
        container_name: mongoclient
        ports:
            - '27018:3000'
        depends_on:
            - db-mongo
        networks:   
            coqui-networks:
                ipv4_address: 172.28.1.5
        deploy:
            resources:
                limits:
                    memory: 100M
                reservations:
                    memory: 20M

    server:
        container_name: coqui_api
        restart: always
        build: '.'
        command: bash -c "npm run migrate:apply && npm start"
        volumes:
            - ./:/node-app
            - ./node_modules:/node-app/node_modules
        env_file: src/enviroments/.env
        environment:
            NODE_ENV: development
            DB_HOST: 173.28.1.2
            DB_PORT: 5432
            DB_USER: root
            DB_PASSWORD: root
            DB_NAME: coqui
            MONGODB_HOST: mongodb://root:root@172.28.1.4:27017/coqui?authSource=admin
        depends_on:
            - db-postgres
        links:
            - db-postgres
        ports:
            - '3001:3001'   
        networks:   
            coqui-networks:
                ipv4_address: 173.28.1.1

networks: 
    coqui-networks:
        ipam:
            driver: default
            config:
                - subnet: 173.28.0.0/16

volumes:
    coqui-docker-data:
        driver: local 